<?php
/**
 * Created by PhpStorm.
 * User: mitryl
 */

const MESSAGE_SET_SHIPS_CORRECTLY = "Разместите корабли правильно";
const MESSAGE_ENEMY_NOT_FOUND = "Противник не найден";
const MESSAGE_ENEMY_NOT_READY = "Другой игрок ещё не готов";
const MESSAGE_YOUR_TURN = "Ваш ход";
const MESSAGE_ENEMY_TURN = "Ход противника";
const MESSAGE_YOU_WIN = "Вы победили";
const MESSAGE_YOU_LOOSE = "Вы проиграли";

?>